services:
  booking_svc:
    build: ../booking_svc
    container_name: booking_svc
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - mongodb
      - kafka

  driver_svc:
    build: ../driver_svc
    container_name: driver_svc
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - mongodb
      - kafka

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper

volumes:
  mongo_data: